/*
 * MyCertificate.java
 * This file was generated by certificate2src
 *   from binary: "/home/build/jenkins-ci/workspace/Customers/Generate-Customer-Certificates/output/sdk/inria.vo/engine/certificates/MyCertificate.bin"
 */
package certificates;

/**
 * The <code>MyCertificate</code> class provides the bytes of the user
 * certificate used to grant the access to the MyScript technologies.
 */
public final class MyCertificate
{
  /**
   * Returns the bytes of the user certificate.
   *
   * @return The bytes of the user certificate.
   */
  public static final byte[] getBytes()
  {
    return BYTES;
  }

  /**
   * The bytes of the user certificate.
   */
  private static final byte[] BYTES = new byte[]{
  };

} // end of: class MyCertificate
